package com.fastcampus.kafkahandson.ugc.inspectedpost;

import com.fastcampus.kafkahandson.ugc.post.model.Post;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public class InspectedPost {
    private Post post;
    private String categoryName;
    private List<String> autoGeneratedTags;
    private LocalDateTime inspectedAt;

    public static InspectedPost generate(
            Post post,
            String categoryName,
            String[] autoGeneratedTags
    ) {
        return new InspectedPost(
                post,
                categoryName,
                Arrays.asList(autoGeneratedTags),
                LocalDateTime.now()
        );
    }
    public static InspectedPost generateForDelete(
            Post post
    ) {
        return new InspectedPost(post,
                null,
                null,
                LocalDateTime.now());
    }

    public Long getId() {
        return post.getId();
    }

    public String getTitle() {
        return post.getTitle();
    }

    public String getContent() {
        return post.getContent();
    }

    public Long getUserId() {
        return post.getUserId();
    }

    public Long getCategoryId() {
        return post.getCategoryId();
    }

    public LocalDateTime getCreatedAt() {
        return post.getCreatedAt();
    }

    public LocalDateTime getUpdatedAt() {
        return post.getUpdatedAt();
    }

    public LocalDateTime getDeletedAt() {
        return post.getDeletedAt();
    }

}
