package com.fastcampus.kafkahandson.ugc.inspectedpost;

import com.fastcampus.kafkahandson.ugc.post.model.Post;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

public record InspectedPost(
        Post post,
        String categoryName,
        List<String> autoGeneratedTags,
        LocalDateTime inspectedAt
) {
    public static InspectedPost generate(
            Post post,
            String categoryName,
            String[] autoGeneratedTags
    ) {
        return new InspectedPost(
                post,
                categoryName,
                Arrays.asList(autoGeneratedTags),
                LocalDateTime.now()
        );
    }
}
