package com.fastcampus.kafkahandson.ugc.adapter.inspectedpost;

import com.fastcampus.kafkahandson.ugc.inspectedpost.InspectedPost;

public class InspectedPostMessageConverter {

    public static InspectedPost toModel(InspectedPostMessage message) {
        return new InspectedPost(
                message.payload().post(),
                message.payload().categoryName(),
                message.payload().autoGeneratedTags(),
                message.payload().inspectedAt()
        );
    }
}
