package com.fastcampus.kafkahandson.ugc.adapter.inspectedpost;

import com.fastcampus.kafkahandson.ugc.adapter.common.OperationType;
import com.fastcampus.kafkahandson.ugc.post.model.Post;

import java.time.LocalDateTime;
import java.util.List;

public record InspectedPostMessage(
        Long id,
        Payload payload,
        OperationType operationType
) {
    public record Payload(
            Post post,
            String categoryName,
            List<String> autoGeneratedTags,
            LocalDateTime inspectedAt
    ) {
    }
}